### ISSUE TITLE
Ceramic-test system doesn't build for me

### ISSUE THREAD

**Issue by quicklisp** [ceramic/ceramic#11]
http://report.quicklisp.org/2015-08-04/failure-report/ceramic.html#ceramic-test has a log. Here's the error I get:

```
;   READ error during COMPILE-FILE: Package CERAMIC.BUNDLER does not exist
```

That's in t/integration.lisp.

**Comment by eudoxia0** [comment]
Right. Here's what happens. If Quicklisp is in the environment, Ceramic loads the bundler. If it isn't -- that is, if you're running the app in production -- then it loads a `ql-patch.lisp` file that just defines the `ql:quickload` function just in case anyone uses it, since dependencies that have `#+quicklisp` are compiled as such and often use this function.

So that's why it won't build. I wouldn't bother running the tests, they take forever.
